---
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and Package
    runs-on: self-hosted

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    env:
      CLI_NAME: loks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $CLI_NAME ./cmd/$CLI_NAME/main.go

      - name: Package binary
        run: |
          tar -czvf $CLI_NAME-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz $CLI_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: $CLI_NAME-${{ matrix.goos }}-${{ matrix.goarch }}
          path: $CLI_NAME-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

  release:
    name: Create GitHub Release
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*.tar.gz
          body: "New version of $CLI_NAME"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
